name: login
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  form_builder_validators: ^8.3.0
  flutter_form_builder: ^7.6.0 
  google_fonts: ^3.0.1 
  http: ^0.13.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  connectivity_plus: ^3.0.2
  flutter_randomcolor: ^1.0.14
  file_picker: ^4.5.1
  open_file: ^3.2.1
  image_picker: ^0.8.6
  curved_navigation_bar: ^1.0.3
  permission_handler: ^10.2.0
  dio: ^4.0.6
  flutter_local_notifications: ^12.0.3
  path_provider: ^2.0.11
  get: ^4.6.5 
  sqflite:
  path:
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/

